GET http://localhost:3002/get-chat-ids

###
GET http://localhost:3002/new-chat

###

GET  http://localhost:3002/get-chat/elon-musk

###
POST http://localhost:3002/continue-chat/elon-musk
Content-Type: application/json

{
    "question": "how many kids"
}